name: Issue Queue
description: Lists all open issues with one of the specified titles
branding:
  icon: list
  color: blue

inputs:
  token:
    description: Personal Access Token
    required: true 
  titles:
    description: Issue titles to select
    required: true

outputs:
  all:
    description: Numbers of all queued issues
    value: ${{ steps.get.outputs.all }}
  next:
    description: Number of next issue
    value: ${{ steps.get.outputs.next }}
  has-next:
    description: Indicates whether or not there is a next issue
    value: ${{ steps.get.outputs.has-next }}
  count:
    description: Number of queued issues
    value: ${{ steps.get.outputs.count }}

runs:
  using: composite
  steps:

    - shell: bash
      id: get
      env:
        TITLES: ${{ inputs.titles }}
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        eval $(
          gh api \
            -H "Accept: application/vnd.github+json" \
            "/repos/$REPOSITORY/issues" \
            --paginate \
            --jq '.[] | {number,title,updated_at}' \
          | jq \
              -r \
              -s \
              '
              [
                env.TITLES
                | split("\n")[]
                | select(. != "")
              ] as $titles
              | [.[] | select(.title as $title | any($titles[]; . == $title))]
              | sort_by(.updated_at | fromdate)
              | map(.number) as $all
              | ($count > 0) as $has_next
              | (if $has_next then .[0].number else -1 end) as $next
              | length as $count
              | "echo \"" +
                "::set-output name=all::\($all | tostring)" +
                "::set-output name=has-next::\($has_next)" +
                "::set-output name=next::\($next)" +
                "::set-output name=count::\($count)\""
              '
          )